<a href="https://colab.research.google.com/github/iIsunnyIi/NLP_Basics/blob/main/word_embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Word Embedding Techniques using Embedding Layer in Keras


##### https://www.youtube.com/watch?v=TsXR7_vtusQ&ab_channel=KrishNaik
##### https://machinelearningmastery.com/use-word-embedding-layers-deep-learning-keras/



1.   Sentences
2.   one hot representation - index from the dictionary
3.   one hot representation - embedding layer keras
4.   From embedding Matrix
5.   Vocab_SIZE = 10K, dimension 10
6.  word representaion with embedding layers



In [ ]:
### Libraries USed Tensorflow> 2.0  and keras
### Tensorflow >2.0 we have Keras integrated with tensorflow
### for tensorflow <2.0 we have to install tensorflow also and keras also and then we have to write the library like this 
#from keras.preprocessing.text import one_hot

In [ ]:
#tensorflow >2.0 so we can use library like this
#from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### initialize the sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
### Vocabulary size: size of dictionary
voc_size=10000

In [5]:
#now converting sentences into one hot reperesentation using library
#tensorflow >2.0 so we can use library like this
from tensorflow.keras.preprocessing.text import one_hot

#### One Hot Representation

In [6]:
#from sentences aprameters is words and vocab size and based on that it would provide you an index from dictionary
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[7926, 4798, 6692, 7634], [7926, 4798, 6692, 7315], [7926, 7081, 6692, 7614], [2817, 2811, 1872, 4079, 8913], [2817, 2811, 1872, 4079, 9737], [9667, 7926, 7751, 6692, 8060], [1261, 4122, 4860, 4079]]


In [ ]:
#so here you can see that each word fo each sentences has index from vocab
#the-5003   glass-760 ... liek that for each sentences out of 10k vocab size

### Word Embedding Represntation

In [ ]:
#now whatever indexes i got i am passing those to embedding layer in keras to form embedding matrix
#important parameters is that how many dimensions i am giving or how many features i am giving
#bcoz this one is feature representaion

In [ ]:
#import embedding layer
#import sequential layer - to create sequence model wrt embedding layer
#pad_sequences - whenever we have to pass anything to embedding layer all sentences should have the same number of words
#for future implementation like in lstm or other size of sentences if same is good 
#in pad sequences parameters goes on are one hot represeantaion and what is padding technique 
#Padding technique
  #in sentence 1 we have 4 words in sentence 5 we have 5 words
  #now to make it word of same size 
  #first assign a maxm (sentences length) so that i can add padding on top of that
  #let say 8 length 
  #using Padding 0 will be alloted to make it 8
  #here using pre as padding .. so at atart 0 is added
  #if post then at last
  #each sentences converted to 8 length words with indexes
  #now pass to embedding layer
  



In [16]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [17]:
import numpy as np

In [18]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7926 4798 6692 7634]
 [   0    0    0    0 7926 4798 6692 7315]
 [   0    0    0    0 7926 7081 6692 7614]
 [   0    0    0 2817 2811 1872 4079 8913]
 [   0    0    0 2817 2811 1872 4079 9737]
 [   0    0    0 9667 7926 7751 6692 8060]
 [   0    0    0    0 1261 4122 4860 4079]]


In [10]:
#now in order to pass to embedding layer we first have to assign a dimension 
#dimension means how many features here we are taking 10
dim=10


In [19]:
#initialize equential model
#parameters (vocab size, dimension, sentence length)
#compile with adam optimizer
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [20]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
#word into featurized vectors 
#10 dimension conversion of each sentences
print(model.predict(embedded_docs))

[[[ 2.6779745e-02 -3.6237109e-02 -3.7982523e-02  2.7177159e-02
    2.6360042e-03 -3.2112934e-02 -2.2621727e-02  1.1148464e-02
    6.2575117e-03  3.0670080e-02]
  [ 2.6779745e-02 -3.6237109e-02 -3.7982523e-02  2.7177159e-02
    2.6360042e-03 -3.2112934e-02 -2.2621727e-02  1.1148464e-02
    6.2575117e-03  3.0670080e-02]
  [ 2.6779745e-02 -3.6237109e-02 -3.7982523e-02  2.7177159e-02
    2.6360042e-03 -3.2112934e-02 -2.2621727e-02  1.1148464e-02
    6.2575117e-03  3.0670080e-02]
  [ 2.6779745e-02 -3.6237109e-02 -3.7982523e-02  2.7177159e-02
    2.6360042e-03 -3.2112934e-02 -2.2621727e-02  1.1148464e-02
    6.2575117e-03  3.0670080e-02]
  [ 4.4261362e-02 -2.8888239e-02 -9.8617189e-03 -6.0929060e-03
   -2.5643421e-02  3.0654561e-02  2.0648096e-02 -4.3946017e-02
    2.3294818e-02  3.2361161e-02]
  [-4.3376911e-02  4.0016625e-02  7.9385415e-03  1.9504432e-02
    3.7369464e-02  2.5986481e-02  2.4765883e-02 -1.7104425e-02
    1.4865588e-02  3.1580497e-02]
  [ 3.8545836e-02 -4.7042537e-02 -8.0499

In [21]:
embedded_docs[0]

array([   0,    0,    0,    0, 7926, 4798, 6692, 7634], dtype=int32)

In [22]:
print(model.predict(embedded_docs)[0])
#10 dimension conversion of each sentences
#first 4 same value bcoz wer have 0 

[[-0.04997096  0.01332024  0.01676859 -0.00822473 -0.01295588  0.00046054
  -0.04379522  0.04422232  0.02976556  0.04102678]
 [-0.04997096  0.01332024  0.01676859 -0.00822473 -0.01295588  0.00046054
  -0.04379522  0.04422232  0.02976556  0.04102678]
 [-0.04997096  0.01332024  0.01676859 -0.00822473 -0.01295588  0.00046054
  -0.04379522  0.04422232  0.02976556  0.04102678]
 [-0.04997096  0.01332024  0.01676859 -0.00822473 -0.01295588  0.00046054
  -0.04379522  0.04422232  0.02976556  0.04102678]
 [-0.04528862  0.02452708  0.01112555 -0.03473718  0.04159046  0.01412637
  -0.02361286 -0.03427856 -0.04098445 -0.01012953]
 [ 0.01505646 -0.0192825   0.0286851   0.01308825 -0.04423837  0.0467946
  -0.03372793  0.00876451  0.02818655 -0.01043538]
 [-0.03352956  0.00681413  0.01862431  0.00162737 -0.04799864  0.00069821
  -0.00953463 -0.04716245  0.02016294  0.00728548]
 [-0.01200349 -0.00850051  0.01342912  0.02234242 -0.04580361  0.03908483
   0.04083658  0.0130605   0.03794545  0.04992094]]
